services:
  - type: web
    name: cover-letter-generator
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "18"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html